# Generated by Django 4.0.7 on 2022-09-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
